#!/usr/bin/env python3
"""Writes unicode_data.vs from llama.cpp's src/unicode-data.cpp (itself
generated from the Unicode database by its scripts/gen-unicode-data.py), so
the pre-tokenizers here classify every codepoint as llama.cpp does.

    python3 tools/gen_unicode.py ~/Desktop/llama.cpp/src/unicode-data.cpp > unicode_data.vs
"""
import re, sys

src = open(sys.argv[1]).read()

def block(name):
    start = src.index(name)
    return src[start:src.index("};", start)]

ranges = re.findall(r"\{0x([0-9A-Fa-f]+), 0x([0-9A-Fa-f]+)\}", block("unicode_ranges_flags"))
spaces = re.findall(r"0x([0-9A-Fa-f]+)", block("unicode_set_whitespace").split("{", 1)[1])

out = []
out.append("// Generated by tools/gen_unicode.py from llama.cpp's src/unicode-data.cpp. Do not edit.")
out.append("package tokenizer")
out.append("")
out.append("// flagRanges is (first codepoint, category flags) pairs, ascending: a")
out.append("// codepoint's flags are those of the last range starting at or below it.")
out.append("let flagRanges: [uint32] = [")
line = "   "
for s, f in ranges:
    item = f" 0x{int(s, 16):X}, 0x{int(f, 16):X},"
    if len(line) + len(item) > 100:
        out.append(line)
        line = "   "
    line += item
out.append(line)
out.append("]")
out.append("")
out.append("// whitespaceSet is the codepoints \\s matches, ascending.")
out.append("let whitespaceSet: [uint32] = [" + ", ".join(f"0x{int(c, 16):X}" for c in spaces) + "]")
print("\n".join(out))
